voice_group mimi_voicegroup_drums @ 8F00600 Custom Voicegroup Drumset
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 255, 165, 154, 127  @ 0 C-2
	voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe, 255, 165, 154, 127  @ 1 C#-2
	voice_directsound 60, 0, DirectSoundWaveData_unused_guitar_separates_power_chord, 255, 165, 206, 127  @ 2 D-2
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 165, 206, 127  @ 3 D#-2
	voice_directsound 60, 0, DirectSoundWaveData_unknown_snare, 255, 0, 255, 0  @ 4 E-2
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_ohtsuzumi, 255, 0, 255, 0  @ 5 F-2
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_hyoushigi, 255, 0, 255, 0  @ 6 F#-2
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 242  @ 7 G-2 RSE Kick (C1)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8 G#-2
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242  @ 9 A-2 RSE Snare (same as G#1)
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127  @ 10 A#-2 Clap (same as D#1)
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242  @ 11 B-2 Snare (same as E1)
	voice_directsound 48, 44, DirectSoundWaveData_unused_sc55_tom, 255, 210, 77, 204  @ 12 C-1 RSE F Tom (F1)
	voice_directsound 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 127, 0, 188  @ 13 C#-1 High Hat (same as F#1)
	voice_directsound 51, 54, DirectSoundWaveData_unused_sc55_tom, 255, 216, 77, 204  @ 14 D-1 RSE G Tom (G1)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 15 D#-1
	voice_directsound 54, 64, DirectSoundWaveData_unused_sc55_tom, 255, 216, 77, 204  @ 16 E-1 RSE A Tom (A1)
	voice_directsound 60, 79, DirectSoundWaveData_unknown_open_hihat, 255, 141, 0, 188  @ 17 F-1 Pedal High Hat (G#1)
	voice_directsound 57, 69, DirectSoundWaveData_unused_sc55_tom, 255, 210, 77, 204  @ 18 F#-1 RSE B Tom (B1)
	voice_directsound 60, 79, DirectSoundWaveData_unused_sc55_tom, 255, 204, 77, 204  @ 19 G-1 RSE C Tom (C1)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 20 G#-1
	voice_directsound 62, 84, DirectSoundWaveData_unused_sc55_tom, 255, 204, 77, 204  @ 21 A-1 RSE D Tom (D2)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 22 A#-1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 23 B-1
	voice_directsound_no_resample 70, 49, DirectSoundWaveData_unknown_bell, 255, 165, 103, 231  @ 24 C0
	voice_directsound_no_resample 32, 34, DirectSoundWaveData_sc88pro_tambourine, 255, 127, 77, 204  @ 25 C#0
	voice_directsound_no_resample 60, 14, DirectSoundWaveData_trinity_cymbal_crash, 255, 235, 0, 165  @ 26 D0
	voice_directsound 60, 64, DirectSoundWaveData_dd_hard_kick, 255, 0, 255, 188  @ 27 D#0
	voice_directsound 60, 64, DirectSoundWaveData_dd_techno_snare, 255, 226, 154, 165  @ 28 E0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 29 F0
	voice_directsound_no_resample 30, 75, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 246, 0, 216  @ 30 F#0 (Sustained Crash)
	voice_directsound_no_resample 30, 64, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 8, 0, 255, 216  @ 31 G0 (Reverse Cymbal)
	voice_directsound 48, 0, DirectSoundWaveData_sc88pro_timpani_with_snare, 255, 254, 0, 226  @ 32 G#0
	voice_directsound 57, 34, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 0  @ 33 A0
	voice_directsound_no_resample 72, 64, DirectSoundWaveData_unknown_snare, 255, 0, 255, 127  @ 34 A#0
	voice_directsound 60, 64, DirectSoundWaveData_drum_and_percussion_kick, 255, 0, 255, 127  @ 35 B0
	voice_directsound 60, 64, DirectSoundWaveData_drum_and_percussion_kick, 255, 0, 255, 0  @ 36 C1
	voice_directsound 60, 64, DirectSoundWaveData_sd90_solo_snare, 255, 180, 175, 228  @ 37 C#1
	voice_directsound 60, 64, DirectSoundWaveData_sd90_solo_snare, 255, 0, 255, 242  @ 38 D1
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127  @ 39 D#1
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242  @ 40 E1
	voice_directsound 64, 24, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 41 F1
	voice_directsound 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 127, 0, 188  @ 42 F#1
	voice_directsound 68, 34, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 43 G1
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242  @ 44 G#1
	voice_directsound 72, 44, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 45 A1
	voice_directsound 60, 79, DirectSoundWaveData_unknown_open_hihat, 255, 242, 141, 204  @ 46 A#1
	voice_directsound 76, 84, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 47 B1
	voice_directsound 80, 94, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 48 C2
	voice_directsound_no_resample 33, 89, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 49 C#2
	voice_directsound 84, 104, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 235  @ 50 D2
	voice_directsound_no_resample 70, 49, DirectSoundWaveData_unknown_bell, 255, 165, 103, 231  @ 51 D#2
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 52 E2
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_dance_drums_ride_bell, 255, 165, 103, 231  @ 53 F2
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_tambourine, 255, 127, 77, 204  @ 54 F#2
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_trinity_cymbal_crash, 255, 231, 0, 188  @ 55 G2
	voice_directsound_no_resample 64, 89, DirectSoundWaveData_sd90_cowbell, 255, 0, 255, 242  @ 56 G#2
	voice_directsound_no_resample 64, 29, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 57 A2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 58 A#2
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 247, 0, 231  @ 59 B2
	voice_directsound_no_resample 64, 69, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 5, 0, 255, 216  @ 60 C3
	voice_directsound_no_resample 64, 94, DirectSoundWaveData_unused_heart_of_asia_indian_drum, 255, 0, 255, 0  @ 61 C#3
	voice_directsound_no_resample 72, 104, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 0  @ 62 D3
	voice_directsound 64, 64, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0  @ 63 D#3
	voice_directsound_no_resample 72, 90, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0  @ 64 E3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 65 F3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 66 F#3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 67 G3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 68 G#3
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_tambourine, 255, 127, 77, 204  @ 69 A3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 70 A#3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 71 B3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 72 C4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 73 C#4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 74 D4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 75 D#4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 76 E4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 77 F4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 78 F#4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 79 G4
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 176, 0, 188  @ 80 G#4
	voice_directsound_no_resample 64, 79, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188  @ 81 A4
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 165, 103, 188  @ 82 A#4
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_sc88pro_jingle_bell, 255, 0, 255, 0  @ 83 B4
	voice_directsound 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 127, 0, 188  @ 84 C5
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 85 C#5
	voice_directsound_no_resample 64, 104, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0  @ 86 D5
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0  @ 87 D#5
	voice_directsound 50, 84, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 0, 255, 0  @ 88 E5
	voice_directsound 64, 84, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 0, 255, 0  @ 89 F5

